import Link from 'next/link'
import { query } from '@/lib/db'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { ArrowLeft } from 'lucide-react'

async function getAnalyses() {
  try {
    const rows = await query<{
      id: string
      patient_name: string | null
      primary_complaint: string | null
      risk_score: string | null
      status: string | null
      created_at: string
    }>(
      `SELECT id, patient_name, primary_complaint, COALESCE(risk_score, 'LOW') AS risk_score, status, created_at
         FROM analysis_runs
        ORDER BY created_at DESC
        LIMIT 50`
    )
    return { rows, error: null }
  } catch (error) {
    console.error('Failed to load analyses', error)
    return { rows: null, error: 'Failed to load analyses. Is the database configured?' }
  }
}

export default async function AnalysesPage() {
  const { rows, error } = await getAnalyses()

  return (
    <main className="min-h-screen bg-slate-50">
      <div className="mx-auto max-w-6xl px-4 py-10 space-y-6">
        <Link href="/">
          <Button variant="ghost" size="sm" className="gap-2 mb-4">
            <ArrowLeft className="h-4 w-4" />
            Back to dashboard
          </Button>
        </Link>
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm text-slate-600">Doctor Workspace</p>
            <h1 className="text-3xl font-bold text-slate-900">Analyses</h1>
            <p className="text-slate-600">Review saved treatment plans generated by the LLM.</p>
          </div>
          <Link href="/intake" className="text-sm text-primary hover:underline">New analysis</Link>
        </div>

        <Card className="shadow-sm">
          <CardHeader>
            <CardTitle>Recent analyses</CardTitle>
            <CardDescription>Newest first (max 50).</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {error && <div className="text-sm text-red-600">{error}</div>}
            {!error && rows && rows.length === 0 && (
              <div className="text-sm text-slate-600">No analyses yet.</div>
            )}
            {!error && rows?.map((a) => (
              <Link key={a.id} href={`/analyses/${a.id}`} className="block rounded-lg border border-slate-100 bg-white px-3 py-2 hover:border-slate-200">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-semibold text-slate-900">{a.patient_name || 'Unknown patient'}</div>
                    <div className="text-sm text-slate-600">{a.primary_complaint || 'Primary complaint not provided'}</div>
                    <div className="text-xs text-slate-500">{new Date(a.created_at).toLocaleString()}</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge className={a.status === 'approved' ? 'bg-emerald-600' : a.status === 'rejected' ? 'bg-red-600' : a.status === 'modified' ? 'bg-amber-500' : 'bg-slate-500'}>
                      {(a.status || 'pending').toUpperCase()}
                    </Badge>
                    <Badge className={a.risk_score === 'HIGH' ? 'bg-red-600' : a.risk_score === 'MEDIUM' ? 'bg-amber-500' : 'bg-emerald-600'}>
                      {(a.risk_score || 'LOW').toUpperCase()}
                    </Badge>
                  </div>
                </div>
              </Link>
            ))}
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
